# Generated by Django 3.1 on 2020-08-24 16:41

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.contrib.postgres.functions.TransactionNow())),
                ('updated_at', models.DateTimeField(default=django.contrib.postgres.functions.TransactionNow())),
                ('origin', models.TextField(max_length=16)),
                ('sku', models.TextField(max_length=16)),
                ('seller_id', models.UUIDField()),
                ('product_code', models.TextField(max_length=64)),
                ('gtin', models.TextField(max_length=14)),
                ('name', models.TextField(max_length=128)),
                ('status', models.TextField(max_length=64)),
                ('brand', models.TextField(max_length=128)),
                ('description', models.TextField()),
                ('free_shipping', models.BooleanField()),
                ('group_id', models.TextField(max_length=16)),
                ('tax_information_id', models.UUIDField(null=True)),
                ('approved', models.BooleanField()),
                ('rejection_reasons', models.JSONField()),
                ('active', models.BooleanField()),
                ('part_number', models.TextField(max_length=32)),
                ('in_campaign', models.BooleanField()),
                ('odin', models.TextField(max_length=64)),
                ('waiting_invoice', models.BooleanField()),
                ('controller_gtin_id', models.UUIDField(null=True)),
                ('currency', models.TextField(max_length=3)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inactive_reason', models.TextField(max_length=64, null=True)),
            ],
        ),
    ]
